image: docker.nexus.infinityhost.eu/rage-java-build:latest

build:
  before_script:
    - docker login docker.nexus.infinityhost.eu -u docker -p ${registry_password}
  script: 
    - cmake .
    - make
  